export const fallbackCourses = [
  {
    id: 1,
    slug: "full-stack-mastery",
    title: "Full Stack Web Development Mastery",
    thumbnail: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80",
    price: 44999,
    discountPrice: 24999,
    category: "Full Stack Training",
    instructor: "Arun Prakash",
    lessonsCount: 92,
    studentsCount: 410,
    rating: 4.8,
    status: "published",
  },
  {
    id: 2,
    slug: "python-placement-bootcamp",
    title: "Python Placement Bootcamp",
    thumbnail: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=900&q=80",
    price: 19999,
    discountPrice: 14999,
    category: "Python",
    instructor: "Priya N",
    lessonsCount: 64,
    studentsCount: 295,
    rating: 4.7,
    status: "published",
  },
  {
    id: 3,
    slug: "oracle-database-admin",
    title: "Oracle Database Administration",
    thumbnail: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=900&q=80",
    price: 18999,
    discountPrice: 12999,
    category: "Oracle",
    instructor: "Karthik M",
    lessonsCount: 55,
    studentsCount: 170,
    rating: 4.6,
    status: "published",
  },
];

export const fallbackQuestions = [
  {
    id: 101,
    slug: "maximum-subarray-kadane",
    title: "Find maximum subarray sum (Kadane's Algorithm)",
    difficulty: "medium",
    domain: "DSA",
    type: "coding",
    tags: ["arrays", "dynamic-programming", "kadane"],
    companies: ["Amazon", "Google", "Zoho"],
    views: 1840,
    bookmarks: 512,
    body: "Given an integer array nums, find the contiguous subarray with the largest sum.",
    hint: "Track best subarray ending at current index.",
    answer: "Use Kadane's algorithm in O(n) time and O(1) space.",
    boilerplate_py: "def max_subarray(nums):\n    # Your code\n    pass",
    test_cases: [
      { input: "[-2,1,-3,4,-1,2,1,-5,4]", expected_output: "6" },
      { input: "[1]", expected_output: "1" },
    ],
  },
  {
    id: 102,
    slug: "design-url-shortener",
    title: "Design a URL Shortener",
    difficulty: "medium",
    domain: "System Design",
    type: "design",
    tags: ["hld", "hashing", "database"],
    companies: ["Amazon", "Freshworks"],
    views: 1211,
    bookmarks: 322,
    body: "Design a URL shortening service like Bit.ly handling 100M URLs.",
    hint: "Discuss API, storage, and unique code generation.",
    answer: "Use Base62 IDs, read-heavy cache, and analytics pipeline.",
    boilerplate_py: "# System design answer space",
    test_cases: [],
  },
];
